import { useAppStore } from "@/state/store";
import { useShallow } from "zustand/react/shallow";

export function useShellFacadeActions() {
  return useAppStore(
    useShallow((state) => ({
      applyProjectedDocument: state.applyProjectedDocument,
      createNewTreeDoc: state.createNewTreeDoc,
      setSelectedPerson: state.setSelectedPerson,
      updatePersonById: state.updatePersonById,
      updateFamilyById: state.updateFamilyById,
      addRelationFromAnchor: state.addRelationFromAnchor,
      createStandalonePerson: state.createStandalonePerson,
      createPersonRecord: state.createPersonRecord,
      linkExistingRelation: state.linkExistingRelation,
      unlinkRelation: state.unlinkRelation,
      setPreset: state.setPreset,
      setDepth: state.setDepth,
      setInclude: state.setInclude,
      toggleShellPanel: state.toggleShellPanel,
      toggleLeftSection: state.toggleLeftSection,
      setLeftSectionState: state.setLeftSectionState,
      setTimelinePanelOpen: state.setTimelinePanelOpen,
      toggleRightStackSection: state.toggleRightStackSection,
      setTimelineScope: state.setTimelineScope,
      setTimelineView: state.setTimelineView,
      setTimelineScaleZoom: state.setTimelineScaleZoom,
      setTimelineScaleOffset: state.setTimelineScaleOffset,
      setTimelineStatus: state.setTimelineStatus,
      clearNodePositions: state.clearNodePositions,
      setGridEnabled: state.setGridEnabled,
      setKindraOrientation: state.setKindraOrientation,
      setKindraLayoutEngine: state.setKindraLayoutEngine,
      toggleKindraNodeCollapse: state.toggleKindraNodeCollapse,
      setOverlay: state.setOverlay,
      clearOverlayType: state.clearOverlayType,
      clearVisualModes: state.clearVisualModes,
      goBack: state.goBack,
      goForward: state.goForward,
      fitToScreen: state.fitToScreen,
      clearRecentFiles: state.clearRecentFiles,
      setMergeDraft: state.setMergeDraft,
      clearMergeDraft: state.clearMergeDraft,
      setAiSettings: state.setAiSettings,
      bootstrapSession: state.bootstrapSession,
      clearSession: state.clearSession,
      dismissRestoreNotice: state.dismissRestoreNotice,
      setFocusFamilyId: state.setFocusFamilyId,
      inspectPerson: state.inspectPerson,
      saveAutosessionNow: state.saveAutosessionNow,
    })),
  );
}
