import type { TreePalette } from "@/views/kindra-v31/overlays/types";

export const TREE_PALETTE: TreePalette = {
  endogamyCases: [
    "var(--tree-case-1)",
    "var(--tree-case-2)",
    "var(--tree-case-3)",
    "var(--tree-case-4)",
    "var(--tree-case-5)",
    "var(--tree-case-6)",
    "var(--tree-case-7)",
    "var(--tree-case-8)"
  ],
  highlight: "var(--tree-highlight)",
  danger: "var(--tree-danger)",
  info: "var(--timeline-type-birt)",
  oldestExact: "var(--tree-oldest-exact)",
  oldestEstimated: "var(--tree-oldest-estimated)",
  oldestDeepest: "var(--tree-oldest-deepest)",
  warning: "var(--tree-warning)",
  success: "var(--tree-success)",
  familyOriginSelf: "var(--tree-family-origin-self)",
  familyOriginGroup: "var(--tree-family-origin-group)",
  oldestExactPath: "var(--tree-oldest-exact-path)",
  oldestEstimatedPath: "var(--tree-oldest-estimated-path)",
  oldestDeepestPath: "var(--tree-oldest-deepest-path)",
  livingFill: "var(--tree-living-fill)",
  livingStroke: "var(--tree-living-stroke)",
  focusStroke: "var(--tree-focus-stroke)",
  selectedStroke: "var(--tree-selected-stroke)",
  warningStroke: "var(--tree-warning-stroke)",
  endogamyChildStroke: "var(--tree-endogamy-child)",
  timelinePrimaryStroke: "var(--tree-highlight-strong)",
  patrilineal: "#0ea5e9",
  matrilineal: "#ec4899",
  combinedLineage: "#a855f7",
  overlayBg: "var(--overlay-panel-bg)",
  overlayBgSoft: "var(--overlay-panel-bg-soft)",
  overlayShadow: "var(--overlay-shadow)",
  overlayText: "var(--overlay-text)",
  overlayTextSoft: "var(--overlay-text-soft)",
  overlayTextMuted: "var(--overlay-text-muted)",
  kinshipAccent: "var(--tree-kinship-accent)"
};
